services:
  fossflow:
    image: wisrovi/fossflow:v1.0 
    pull_policy: always
    ports:
      - 15380:80
    environment:
      - NODE_ENV=production
      - ENABLE_SERVER_STORAGE=${ENABLE_SERVER_STORAGE:-true}
      - STORAGE_PATH=/data/diagrams
      - ENABLE_GIT_BACKUP=${ENABLE_GIT_BACKUP:-false}
    volumes:
      - ./diagrams:/data/diagrams
